services:
  - type: web
    name: transit-sng
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: "10000"
