
name: transitsng_mobile
description: TransitSNG mobile app (Flutter) - full UI similar to web
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.2
  intl: ^0.19.0
  socket_io_client: ^2.0.0
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
