
name: transitsng_mobile
description: TransitSNG mobile app skeleton with location tracking (demo)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  socket_io_client: ^2.0.0
  geolocator: ^9.0.2
  flutter_localizations:
    sdk: flutter
