name: transitsng_mobile
description: TransitSNG mobile skeleton
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
