
name: Build Android (APK & AAB)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      BUILD_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: flutter pub get
        run: flutter pub get
        working-directory: ./mobile

      - name: Build release APK
        run: flutter build apk --release --split-per-abi
        working-directory: ./mobile

      - name: Build app bundle (AAB)
        run: flutter build appbundle --release
        working-directory: ./mobile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TransitSNG-android-artifacts
          path: |
            mobile/build/app/outputs/flutter-apk/*.apk
            mobile/build/app/outputs/bundle/release/*.aab
